---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "9990"
    prometheus.io/scrape: "true"
  labels:
    app: conntest
    project: conntest
  name: conntest
spec:
  clusterIP: None
  ports:
  - name: tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: prometheus
    port: 9990
    protocol: TCP
    targetPort: prometheus
  selector:
    app: conntest
