go_library(
    name = "srvendpoints",
    srcs = ["srvendpoints.go"],
    visibility = ["PUBLIC"],
    deps = [
        "//third_party/go:logrus",
        "//src/tcpconn:tcpconn",
        "//third_party/go:prometheus",
    ],
)
